const STORAGE_KEY = 'studyflow-v1';
const today = new Date().toISOString().slice(0, 10);
const seed = { subjects: [
  { id: 'maths', name: 'Mathematics', color: 'purple', chapters: [{ title: 'Real Numbers', done: true }, { title: 'Polynomials', done: true }, { title: 'Linear Equations', done: false }] },
  { id: 'science', name: 'Science', color: 'green', chapters: [{ title: 'Chemical Reactions', done: true }, { title: 'Life Processes', done: false }, { title: 'Light', done: false }] },
  { id: 'english', name: 'English', color: 'coral', chapters: [{ title: 'First Flight', done: true }, { title: 'Footprints Without Feet', done: false }] }
], sessions: [{ id: 's1', subjectId: 'maths', minutes: 65, date: today, note: 'Practised numericals' }, { id: 's2', subjectId: 'science', minutes: 45, date: today, note: 'Read chapter notes' }], tests: [{ id: 't1', subjectId: 'maths', title: 'Algebra quiz', score: 18, total: 20 }] };
let state = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || seed;
const $ = (selector) => document.querySelector(selector);
const save = () => localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
const minutesLabel = (minutes) => `${Math.floor(minutes / 60)}h ${String(minutes % 60).padStart(2, '0')}m`;
const subject = (id) => state.subjects.find((item) => item.id === id);

function renderOptions() { const options = state.subjects.map((item) => `<option value="${item.id}">${item.name}</option>`).join(''); document.querySelectorAll('.subject-options').forEach((el) => { el.innerHTML = options || '<option value="">Add a subject first</option>'; el.disabled = !state.subjects.length; }); }
function renderDashboard() {
  const chapters = state.subjects.flatMap((item) => item.chapters); const done = chapters.filter((item) => item.done).length;
  const totalMinutes = state.sessions.reduce((sum, item) => sum + Number(item.minutes), 0); const dailyMinutes = state.sessions.filter((item) => item.date === today).reduce((sum, item) => sum + Number(item.minutes), 0);
  const avg = state.tests.length ? Math.round(state.tests.reduce((sum, item) => sum + (item.score / item.total) * 100, 0) / state.tests.length) : null;
  $('#completed-stat').innerHTML = `${done}<span>/${chapters.length}</span>`; $('#completed-copy').textContent = chapters.length ? `${Math.round(done / chapters.length * 100)}% syllabus complete` : 'Start your first chapter';
  $('#study-stat').innerHTML = `${Math.floor(totalMinutes / 60)}h <span>${totalMinutes % 60}m</span>`; $('#study-copy').textContent = state.sessions.length ? `${state.sessions.length} focus sessions logged` : 'No sessions logged yet';
  $('#marks-stat').textContent = avg === null ? '—' : `${avg}%`; $('#marks-copy').textContent = avg === null ? 'Add a test result' : `${state.tests.length} assessment${state.tests.length === 1 ? '' : 's'} recorded`;
  $('#goal-side').textContent = minutesLabel(dailyMinutes); $('#goal-side-bar').style.width = `${Math.min(dailyMinutes / 120 * 100, 100)}%`;
  const week = Array.from({ length: 7 }, (_, index) => { const d = new Date(); d.setDate(d.getDate() - 6 + index); const date = d.toISOString().slice(0, 10); return state.sessions.filter((item) => item.date === date).reduce((sum, item) => sum + Number(item.minutes), 0); });
  const max = Math.max(...week, 60); $('#weekly-chart').innerHTML = week.map((value) => `<div class="bar-wrap"><div class="bar" title="${minutesLabel(value)}" style="height:${Math.max(value / max * 100, 3)}%"></div></div>`).join('');
  const next = state.subjects.flatMap((item) => item.chapters.filter((chapter) => !chapter.done).map((chapter) => ({ ...chapter, subject: item }))).slice(0, 3);
  $('#up-next').innerHTML = next.length ? next.map((chapter) => `<div class="next-item"><i class="next-dot ${chapter.subject.color}"></i><div><strong>${chapter.title}</strong><span>${chapter.subject.name}</span></div><button class="text-button chapter-quick" data-subject="${chapter.subject.id}" data-chapter="${chapter.title}">Done</button></div>`).join('') : '<p class="empty-state">Amazing — every chapter is complete!</p>';
}
function renderSubjects() { $('#subjects-list').innerHTML = state.subjects.length ? state.subjects.map((item) => { const done = item.chapters.filter((chapter) => chapter.done).length; const pct = item.chapters.length ? done / item.chapters.length * 100 : 0; return `<article class="subject-card ${item.color}"><div class="subject-top"><span class="subject-icon">${item.name.slice(0, 1)}</span><button class="subject-actions delete-subject" data-id="${item.id}" aria-label="Delete ${item.name}">×</button></div><h3>${item.name}</h3><p>${done} of ${item.chapters.length} chapters complete</p><div class="progress-track"><i style="width:${pct}%"></i></div><div class="subject-footer"><span>${Math.round(pct)}% complete</span><span>${item.chapters.length - done} remaining</span></div><ul class="chapter-list">${item.chapters.slice(0, 3).map((chapter, index) => `<li><input type="checkbox" class="chapter-check" data-subject="${item.id}" data-index="${index}" ${chapter.done ? 'checked' : ''}/><span>${chapter.title}</span></li>`).join('')}</ul><button class="chapter-add" data-chapter-for="${item.id}">+ Add chapter</button></article>`; }).join('') : '<p class="empty-state">No subjects yet. Add your first one to begin.</p>'; }
function renderLogs() { $('#sessions-list').innerHTML = state.sessions.length ? [...state.sessions].reverse().slice(0, 6).map((item) => `<div class="log-item"><span class="log-icon">◷</span><div class="log-main"><strong>${subject(item.subjectId)?.name || 'Subject'}</strong><span>${item.note || 'Focused study'} · ${item.date}</span></div><span class="log-value">${minutesLabel(item.minutes)}</span><button class="delete-button delete-session" data-id="${item.id}" aria-label="Delete session">×</button></div>`).join('') : '<p class="empty-state">Your study sessions will appear here.</p>'; $('#tests-list').innerHTML = state.tests.length ? [...state.tests].reverse().map((item) => `<div class="log-item"><span class="log-icon">▤</span><div class="log-main"><strong>${item.title}</strong><span>${subject(item.subjectId)?.name || 'Subject'}</span></div><span class="log-value">${item.score}/${item.total} · ${Math.round(item.score / item.total * 100)}%</span><button class="delete-button delete-test" data-id="${item.id}" aria-label="Delete test">×</button></div>`).join('') : '<p class="empty-state">Your test results will appear here.</p>'; }
function render() { renderOptions(); renderDashboard(); renderSubjects(); renderLogs(); save(); }
function openModal(id) { if (!state.subjects.length && id !== 'subject-modal') { openModal('subject-modal'); return; } $(`#${id}`).showModal(); $('#modal-backdrop').classList.add('open'); }
function closeModals() { document.querySelectorAll('dialog[open]').forEach((modal) => modal.close()); $('#modal-backdrop').classList.remove('open'); }
document.addEventListener('click', (event) => { const open = event.target.closest('[data-open-modal]'); if (open) openModal(open.dataset.openModal); if (event.target.matches('.close-modal, #modal-backdrop')) closeModals(); const add = event.target.closest('[data-chapter-for]'); if (add) { $('#chapter-form [name="subjectId"]').value = add.dataset.chapterFor; openModal('chapter-modal'); } const check = event.target.closest('.chapter-check'); if (check) { subject(check.dataset.subject).chapters[check.dataset.index].done = check.checked; render(); } const quick = event.target.closest('.chapter-quick'); if (quick) { const chapter = subject(quick.dataset.subject).chapters.find((item) => item.title === quick.dataset.chapter); chapter.done = true; render(); } const delSub = event.target.closest('.delete-subject'); if (delSub) { state.subjects = state.subjects.filter((item) => item.id !== delSub.dataset.id); state.sessions = state.sessions.filter((item) => item.subjectId !== delSub.dataset.id); state.tests = state.tests.filter((item) => item.subjectId !== delSub.dataset.id); render(); } const delSession = event.target.closest('.delete-session'); if (delSession) { state.sessions = state.sessions.filter((item) => item.id !== delSession.dataset.id); render(); } const delTest = event.target.closest('.delete-test'); if (delTest) { state.tests = state.tests.filter((item) => item.id !== delTest.dataset.id); render(); } });
$('#subject-form').addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.target); state.subjects.push({ id: crypto.randomUUID(), name: data.get('name'), color: data.get('color'), chapters: [] }); event.target.reset(); closeModals(); render(); });
$('#chapter-form').addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.target); subject(data.get('subjectId')).chapters.push({ title: data.get('title'), done: false }); event.target.reset(); closeModals(); render(); });
$('#session-form').addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.target); state.sessions.push({ id: crypto.randomUUID(), subjectId: data.get('subjectId'), minutes: Number(data.get('minutes')), date: data.get('date'), note: data.get('note') }); event.target.reset(); closeModals(); render(); });
$('#test-form').addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.target); state.tests.push({ id: crypto.randomUUID(), subjectId: data.get('subjectId'), title: data.get('title'), score: Number(data.get('score')), total: Number(data.get('total')) }); event.target.reset(); closeModals(); render(); });
function toggleTheme() { document.body.classList.toggle('dark'); localStorage.setItem('studyflow-theme', document.body.classList.contains('dark') ? 'dark' : 'light'); }
$('#theme-toggle').addEventListener('click', toggleTheme); $('#theme-toggle-mobile').addEventListener('click', toggleTheme); $('#mobile-menu').addEventListener('click', () => $('.sidebar').classList.toggle('open'));
if (localStorage.getItem('studyflow-theme') === 'dark') document.body.classList.add('dark'); $('#session-form [name="date"]').value = today; render();
